# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a2c482f870c53e08e32313cd3b73c1938ba2906d24c5f75d96438672a7cd6b391b83504d2842f9c2fe1f1c9ffa92dc027f9093b341cea84b1490af5e97c976d

test:
  secret_key_base: 7319c3ffb9ed8b4d0e952a37bb83eb9173f0523b43aad4b10c5ab5ac615afa6f94a72edce12b192d00a7349a6dd87ab4fd2268c4f8db5f3b72396e391dbdca11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
